
const bloquesFijos = {
  "Bloque 1": [
    { palabra: "conspicuo", sinonimos: ["ilustre"] },
    { palabra: "inicuo", sinonimos: ["malvado"] },
    { palabra: "dadivoso", sinonimos: ["generoso"] },
    { palabra: "taciturno", sinonimos: ["callado"] },
    { palabra: "derogar", sinonimos: ["anular"] },
    { palabra: "feraz", sinonimos: ["fértil"] },
    { palabra: "altivez", sinonimos: ["orgullo"] },
    { palabra: "languidecer", sinonimos: ["debilitarse"] },
    { palabra: "mesura", sinonimos: ["prudencia"] },
    { palabra: "luctuoso", sinonimos: ["doloroso"] },
    { palabra: "malsín", sinonimos: ["difamador"] },
    { palabra: "abyecto", sinonimos: ["vil", "ruin"] },
    { palabra: "acervo", sinonimos: ["patrimonio"] },
    { palabra: "narciso", sinonimos: ["vanidoso"] },
    { palabra: "aciago", sinonimos: ["desgraciado"] },
    { palabra: "escéptico", sinonimos: ["incrédulo"] },
    { palabra: "displicencia", sinonimos: ["indiferencia"] },
    { palabra: "irrisorias", sinonimos: ["ridículas"] },
    { palabra: "escarnio", sinonimos: ["burla"] },
    { palabra: "lenitivo", sinonimos: ["calmante"] },
    { palabra: "fulgor", sinonimos: ["brillo"] },
    { palabra: "encono", sinonimos: ["odio", "rencor"] },
    { palabra: "lisonja", sinonimos: ["adulación"] },
    { palabra: "furibundo", sinonimos: ["colérico"] },
    { palabra: "vacuo", sinonimos: ["vacío"] },
    { palabra: "bizantinas", sinonimos: ["irrelevante"] },
    { palabra: "quimera", sinonimos: ["ilusión"] }
  ],
  "Bloque 2": [
    { palabra: "dimitir", sinonimos: ["renunciar"] },
    { palabra: "zaherir", sinonimos: ["humillar"] },
    { palabra: "aherrojar", sinonimos: ["aprisionar"] },
    { palabra: "epifanía", sinonimos: ["revelación"] },
    { palabra: "sindicar", sinonimos: ["acusar", "señalar"] },
    { palabra: "manumiso", sinonimos: ["liberado"] },
    { palabra: "pingüe", sinonimos: ["abundante"] },
    { palabra: "atiborrado", sinonimos: ["lleno"] },
    { palabra: "lóbrego", sinonimos: ["oscuro"] },
    { palabra: "promulgar", sinonimos: ["difundir"] },
    { palabra: "ingentes", sinonimos: ["grande"] },
    { palabra: "exiguas", sinonimos: ["pequeño"] },
    { palabra: "deceso", sinonimos: ["muerte"] },
    { palabra: "copioso", sinonimos: ["abundante"] },
    { palabra: "borroso", sinonimos: ["dudoso"] },
    { palabra: "vejar", sinonimos: ["humillar"] },
    { palabra: "oprobio", sinonimos: ["deshonra"] },
    { palabra: "prescindir", sinonimos: ["excluir"] },
    { palabra: "mitigar", sinonimos: ["reducir"] },
    { palabra: "resarcir", sinonimos: ["compensar"] },
    { palabra: "sedición", sinonimos: ["rebelión"] },
    { palabra: "vindicar", sinonimos: ["redimir"] },
    { palabra: "ojeriza", sinonimos: ["enojo"] },
    { palabra: "bisoño", sinonimos: ["principiante"] },
    { palabra: "riada", sinonimos: ["inundación"] },
    { palabra: "inerme", sinonimos: ["indefenso"] }
  ]
};
let bloques = { ...bloquesFijos };
