
const bloquesFijos = {
  "Bloque 1": [
    { palabra: "conspicuo", sinonimos: ["ilustre"] },
    { palabra: "inicuo", sinonimos: ["malvado"] },
    { palabra: "dadivoso", sinonimos: ["generoso"] },
    { palabra: "taciturno", sinonimos: ["callado"] },
    { palabra: "derogar", sinonimos: ["anular"] },
    { palabra: "feraz", sinonimos: ["fértil"] },
    { palabra: "altivez", sinonimos: ["orgullo"] },
    { palabra: "languidecer", sinonimos: ["debilitarse"] },
    { palabra: "mesura", sinonimos: ["prudencia"] },
    { palabra: "luctuoso", sinonimos: ["doloroso"] },
    { palabra: "malsín", sinonimos: ["difamador"] },
    { palabra: "abyecto", sinonimos: ["vil", "ruin"] },
    { palabra: "acervo", sinonimos: ["patrimonio"] },
    { palabra: "narciso", sinonimos: ["vanidoso"] },
    { palabra: "aciago", sinonimos: ["desgraciado"] },
    { palabra: "escéptico", sinonimos: ["incrédulo"] },
    { palabra: "displicencia", sinonimos: ["indiferencia"] },
    { palabra: "irrisorias", sinonimos: ["ridículas"] },
    { palabra: "escarnio", sinonimos: ["burla"] },
    { palabra: "lenitivo", sinonimos: ["calmante"] },
    { palabra: "fulgor", sinonimos: ["brillo"] },
    { palabra: "encono", sinonimos: ["odio", "rencor"] },
    { palabra: "lisonja", sinonimos: ["adulación"] },
    { palabra: "furibundo", sinonimos: ["colérico"] },
    { palabra: "vacuo", sinonimos: ["vacío"] },
    { palabra: "bizantinas", sinonimos: ["irrelevante"] },
    { palabra: "quimera", sinonimos: ["ilusión"] }
  ],
  "Bloque 2": [
    { palabra: "dimitir", sinonimos: ["renunciar"] },
    { palabra: "zaherir", sinonimos: ["humillar"] },
    { palabra: "aherrojar", sinonimos: ["aprisionar"] },
    { palabra: "epifanía", sinonimos: ["revelación"] },
    { palabra: "sindicar", sinonimos: ["acusar", "señalar"] },
    { palabra: "manumiso", sinonimos: ["liberado"] },
    { palabra: "pingüe", sinonimos: ["abundante"] },
    { palabra: "atiborrado", sinonimos: ["lleno"] },
    { palabra: "lóbrego", sinonimos: ["oscuro"] },
    { palabra: "promulgar", sinonimos: ["difundir"] },
    { palabra: "ingentes", sinonimos: ["grande"] },
    { palabra: "exiguas", sinonimos: ["pequeño"] },
    { palabra: "deceso", sinonimos: ["muerte"] },
    { palabra: "copioso", sinonimos: ["abundante"] },
    { palabra: "borroso", sinonimos: ["dudoso"] },
    { palabra: "vejar", sinonimos: ["humillar"] },
    { palabra: "oprobio", sinonimos: ["deshonra"] },
    { palabra: "prescindir", sinonimos: ["excluir"] },
    { palabra: "mitigar", sinonimos: ["reducir"] },
    { palabra: "resarcir", sinonimos: ["compensar"] },
    { palabra: "sedición", sinonimos: ["rebelión"] },
    { palabra: "vindicar", sinonimos: ["redimir"] },
    { palabra: "ojeriza", sinonimos: ["enojo"] },
    { palabra: "bisoño", sinonimos: ["principiante"] },
    { palabra: "riada", sinonimos: ["inundación"] },
    { palabra: "inerme", sinonimos: ["indefenso"] }
  ],
  "Bloque 3": [
    { palabra: "aliñado", sinonimos: ["arreglado"] },
    { palabra: "galano", sinonimos: ["elegante"] },
    { palabra: "nadería", sinonimos: ["trivial"] },
    { palabra: "suntuoso", sinonimos: ["costoso"] },
    { palabra: "perpetrador", sinonimos: ["delito"] },
    { palabra: "exordio", sinonimos: ["introducir"] },
    { palabra: "introito", sinonimos: ["entrada"] },
    { palabra: "mañero", sinonimos: ["manejable", "hábil"] },
    { palabra: "jaleo", sinonimos: ["alboroto"] },
    { palabra: "desvergüenza", sinonimos: ["cinismo"] },
    { palabra: "displicencia", sinonimos: ["indiferencia"] },
    { palabra: "aplotmo", sinonimos: ["serenidad"] },
    { palabra: "preludio", sinonimos: ["comienzo"] },
    { palabra: "insimientes", sinonimos: ["ignorante"] },
    { palabra: "insurgente", sinonimos: ["rebelde"] },
    { palabra: "utopía", sinonimos: ["idea"] },
    { palabra: "vituperio", sinonimos: ["crítica", "dura"] },
    { palabra: "egregio", sinonimos: ["ilustre", "distinguido"] },
    { palabra: "incuria", sinonimos: ["descuido"] },
    { palabra: "pericia", sinonimos: ["habilidad"] }

  ,
  "Bloque 4": [
    { palabra: "inhumar", sinonimos: ["enterrar"] },
    { palabra: "furibunda", sinonimos: ["airada"] },
    { palabra: "venturosa", sinonimos: ["afortunada"] },
    { palabra: "exultante", sinonimos: ["jubiloso"] },
    { palabra: "desidia", sinonimos: ["desinteres"] },
    { palabra: "pusilanimidad", sinonimos: ["cobardía"] },
    { palabra: "lacónicamente", sinonimos: ["brevemente"] },
    { palabra: "tedio", sinonimos: ["aburrimiento"] },
    { palabra: "cicatería", sinonimos: ["tacañería"] },
    { palabra: "ingente", sinonimos: ["enorme"] },
    { palabra: "inhóspito", sinonimos: ["desagradable"] },
    { palabra: "baladí", sinonimos: ["trivial"] },
    { palabra: "profuso", sinonimos: ["abundante"] },
    { palabra: "fútil", sinonimos: ["inútil"] },
    { palabra: "vilipendiar", sinonimos: ["despreciar"] },
    { palabra: "ignoto", sinonimos: ["nodescubierto"] },
    { palabra: "quimera", sinonimos: ["ilusión"] },
    { palabra: "oneroso", sinonimos: ["costoso"] },
    { palabra: "élite", sinonimos: ["minoría"] },
    { palabra: "inicuo", sinonimos: ["injusto"] },
    { palabra: "aplotmo", sinonimos: ["serenidad"] },
    { palabra: "radical", sinonimos: ["extremo"] },
    { palabra: "supeditar", sinonimos: ["subordinar"] },
    { palabra: "capaz", sinonimos: ["hábil"] },
    { palabra: "longevidad", sinonimos: ["largavida"] },
    { palabra: "ludibrio", sinonimos: ["burla"] },
    { palabra: "austero", sinonimos: ["sobrio"] },
    { palabra: "vituperio", sinonimos: ["insulto"] },
    { palabra: "próspero", sinonimos: ["exitoso"] },
    { palabra: "satisfecho", sinonimos: ["complacido"] },
    { palabra: "sedicioso", sinonimos: ["rebelde"] },
    { palabra: "vehemencia", sinonimos: ["pasión"] },
    { palabra: "temerario", sinonimos: ["audaz"] }
  ],
  "Bloque 5": [
    { palabra: "inerte", sinonimos: ["inmóvil"] },
    { palabra: "inverne", sinonimos: ["insensible"] },
    { palabra: "condensar", sinonimos: ["compactar"] },
    { palabra: "candoroso", sinonimos: ["ingenuo"] },
    { palabra: "suspicaz", sinonimos: ["desconfiado"] },
    { palabra: "desdeñar", sinonimos: ["despreciar"] },
    { palabra: "exhumar", sinonimos: ["desenterrar"] },
    { palabra: "extenuado", sinonimos: ["cansado"] },
    { palabra: "obnubilado", sinonimos: ["confundido"] },
    { palabra: "paupérrimo", sinonimos: ["pobre"] },
    { palabra: "felonía", sinonimos: ["traición"] }
  ],
  "Bloque 6": [
    { palabra: "pesaroso", sinonimos: ["apesadumbrado"] },
    { palabra: "lúgubre", sinonimos: ["tétrico", "oscuro"] },
    { palabra: "decrépito", sinonimos: ["viejo", "ajado"] },
    { palabra: "timorato", sinonimos: ["miedoso"] },
    { palabra: "fatuo", sinonimos: ["vanidoso"] },
    { palabra: "frívolo", sinonimos: ["trivial"] },
    { palabra: "deletéreo", sinonimos: ["dañino"] },
    { palabra: "celeste", sinonimos: ["divino"] },
    { palabra: "escueto", sinonimos: ["breve"] },
    { palabra: "crucial", sinonimos: ["fundamental", "esencial"] },
    { palabra: "vital", sinonimos: ["esencial"] },
    { palabra: "manumitir", sinonimos: ["liberar"] },
    { palabra: "repatriación", sinonimos: ["retorno"] },
    { palabra: "paradójico", sinonimos: ["contradicción"] },
    { palabra: "vericuetos", sinonimos: ["laberintos"] },
    { palabra: "felonía", sinonimos: ["traición"] },
    { palabra: "atavío", sinonimos: ["vestimenta"] },
    { palabra: "abdicar", sinonimos: ["renunciar"] },
    { palabra: "ordinario", sinonimos: ["común"] },
    { palabra: "vanagloria", sinonimos: ["jactancia"] },
    { palabra: "vulnerable", sinonimos: ["débil"] },
    { palabra: "imprescindible", sinonimos: ["esencial"] },
    { palabra: "fruslería", sinonimos: ["insignificancia"] },
    { palabra: "impávido", sinonimos: ["sereno"] },
    { palabra: "sempiterno", sinonimos: ["eterno"] },
    { palabra: "impugnar", sinonimos: ["contradecir"] },
    { palabra: "cruento", sinonimos: ["sangriento"] },
    { palabra: "enaltecido", sinonimos: ["exaltado"] },
    { palabra: "conmina", sinonimos: ["amenaza"] },
    { palabra: "prolijo", sinonimos: ["cuidadoso"] },
    { palabra: "dimisión", sinonimos: ["renuncia"] },
    { palabra: "impeler", sinonimos: ["impulsar"] },
    { palabra: "pifia", sinonimos: ["error"] },
    { palabra: "desavenencia", sinonimos: ["discordia"] },
    { palabra: "síncopa", sinonimos: ["reducción"] },
    { palabra: "sensato", sinonimos: ["prudente", "sabio"] },
    { palabra: "lumbrera", sinonimos: ["sabio"] },
    { palabra: "abrupto", sinonimos: ["brusco"] },
    { palabra: "ineluctable", sinonimos: ["inevitable"] },
    { palabra: "trapacería", sinonimos: ["engaño", "picardía"] },
    { palabra: "tránsfuga", sinonimos: ["desertor"] },
    { palabra: "desertor", sinonimos: ["traidor"] },
    { palabra: "áulico", sinonimos: ["cortés"] }
  ]

  ]
};


  ,
  "Bloque 7": [
    { palabra: "verídico", sinonimos: ["verdadero"] },
    { palabra: "predominante", sinonimos: ["principal"] },
    { palabra: "autóctono", sinonimos: ["nativo"] },
    { palabra: "patrocinar", sinonimos: ["auspiciar"] },
    { palabra: "lúdico", sinonimos: ["recreativo"] },
    { palabra: "cáustico", sinonimos: ["mordaz"] },
    { palabra: "objetividad", sinonimos: ["imparcialidad"] },
    { palabra: "statuquo", sinonimos: ["situación"] },
    { palabra: "persuadir", sinonimos: ["convencer"] },
    { palabra: "palidecer", sinonimos: ["descolorarse"] },
    { palabra: "turbación", sinonimos: ["confusión"] },
    { palabra: "lividez", sinonimos: ["palidez"] },
    { palabra: "pasmo", sinonimos: ["asombro"] },
    { palabra: "impasible", sinonimos: ["sereno"] },
    { palabra: "estoico", sinonimos: ["firme"] },
    { palabra: "afable", sinonimos: ["amable"] },
    { palabra: "adusto", sinonimos: ["severo"] },
    { palabra: "abstruso", sinonimos: ["complicado"] },
    { palabra: "mirífico", sinonimos: ["admirable"] },
    { palabra: "garboso", sinonimos: ["elegante"] },
    { palabra: "altivo", sinonimos: ["arrogante"] },
    { palabra: "jactarse", sinonimos: ["presumir"] },
    { palabra: "atildado", sinonimos: ["pulcro"] },
    { palabra: "mesurado", sinonimos: ["moderado"] },
    { palabra: "remitir", sinonimos: ["enviar"] },
    { palabra: "enhiesto", sinonimos: ["erguido"] },
    { palabra: "inerme", sinonimos: ["indefenso"] },
    { palabra: "obstá", sinonimos: ["impide"] },
    { palabra: "cicatero", sinonimos: ["tacaño"] },
    { palabra: "abstracción", sinonimos: ["aislamiento"] },
    { palabra: "alegato", sinonimos: ["discurso"] },
    { palabra: "antagonismo", sinonimos: ["rivalidad"] },
    { palabra: "celeridad", sinonimos: ["rapidez"] },
    { palabra: "corroborar", sinonimos: ["confirmar"] },
    { palabra: "desdeñar", sinonimos: ["despreciar"] },
    { palabra: "derrotero", sinonimos: ["rumbo"] },
    { palabra: "dilucidar", sinonimos: ["aclarar"] }
  ],
  "Bloque 8": [
    { palabra: "esporádico", sinonimos: ["ocasional"] },
    { palabra: "frivolidad", sinonimos: ["superficialidad"] },
    { palabra: "inmutable", sinonimos: ["constante"] },
    { palabra: "lucro", sinonimos: ["ganancia"] },
    { palabra: "menoscabar", sinonimos: ["dañar"] },
    { palabra: "postrimerías", sinonimos: ["final"] },
    { palabra: "prescindir", sinonimos: ["omitir"] },
    { palabra: "proliferar", sinonimos: ["multiplicarse"] },
    { palabra: "relievar", sinonimos: ["destacar"] },
    { palabra: "sesgo", sinonimos: ["parcialidad"] },
    { palabra: "veleidad", sinonimos: ["capricho"] },
    { palabra: "veto", sinonimos: ["prohibición"] },
    { palabra: "congruencia", sinonimos: ["coherencia"] },
    { palabra: "crónico", sinonimos: ["persistente"] },
    { palabra: "devenir", sinonimos: ["transformación"] },
    { palabra: "disentir", sinonimos: ["discrepar"] },
    { palabra: "estentóreo", sinonimos: ["ruidoso"] },
    { palabra: "fiscalizar", sinonimos: ["vigilar"] },
    { palabra: "fonético", sinonimos: ["sonoro"] },
    { palabra: "gama", sinonimos: ["variedad"] },
    { palabra: "gradual", sinonimos: ["progresivo"] },
    { palabra: "inculcar", sinonimos: ["enseñar"] },
    { palabra: "mitigar", sinonimos: ["aliviar"] },
    { palabra: "precariedad", sinonimos: ["escasez"] },
    { palabra: "propenso", sinonimos: ["inclinado"] },
    { palabra: "purga", sinonimos: ["expulsión"] },
    { palabra: "risible", sinonimos: ["cómico"] },
    { palabra: "sempiterno", sinonimos: ["eterno"] },
    { palabra: "sondeo", sinonimos: ["encuesta"] },
    { palabra: "súbito", sinonimos: ["repentino"] },
    { palabra: "yerro", sinonimos: ["error"] },
    { palabra: "zozobra", sinonimos: ["angustia"] },
    { palabra: "abolir", sinonimos: ["suprimir"] },
    { palabra: "avalar", sinonimos: ["respaldar"] },
    { palabra: "aducir", sinonimos: ["alegar"] },
    { palabra: "anuencia", sinonimos: ["aprobación"] },
    { palabra: "exento", sinonimos: ["liberado"] }
  ],
  "Bloque 9": [
    { palabra: "férreo", sinonimos: ["estricto"] },
    { palabra: "hacinar", sinonimos: ["amontonar"] },
    { palabra: "heteróclito", sinonimos: ["extraño"] },
    { palabra: "inherente", sinonimos: ["esencial"] },
    { palabra: "jingoísmo", sinonimos: ["nacionalismo"] },
    { palabra: "monipodio", sinonimos: ["inflorescencia"] },
    { palabra: "mezquino", sinonimos: ["miserable"] },
    { palabra: "plausible", sinonimos: ["razonable"] },
    { palabra: "pretérito", sinonimos: ["pasado"] },
    { palabra: "ralentizar", sinonimos: ["retardar"] },
    { palabra: "secuela", sinonimos: ["consecuencia"] },
    { palabra: "semántico", sinonimos: ["lingüístico"] },
    { palabra: "teratológico", sinonimos: ["deformado"] },
    { palabra: "virulencia", sinonimos: ["agresividad"] },
    { palabra: "concurrir", sinonimos: ["asistir"] },
    { palabra: "vatcinar", sinonimos: ["predecir"] },
    { palabra: "vestigio", sinonimos: ["rastro"] },
    { palabra: "melifluo", sinonimos: ["empalagoso"] },
    { palabra: "sutil", sinonimos: ["delicado"] },
    { palabra: "agobiante", sinonimos: ["abrumador"] },
    { palabra: "postulado", sinonimos: ["principio"] },
    { palabra: "coacción", sinonimos: ["imposición"] },
    { palabra: "cognición", sinonimos: ["conocimiento"] },
    { palabra: "egocéntrico", sinonimos: ["narcisista"] },
    { palabra: "relativo", sinonimos: ["vinculado"] }
  ]
};
let bloques = { ...bloquesFijos };
